// MountingHole_2.2mm_M2_Pad_Via, verbatim from the official KiCad footprint
// library (MountingHole.pretty), kept in sync with whatever ships in
// /usr/share/kicad/footprints/MountingHole.pretty/ -- this is the upstream
// design, not a community copy, so there's nothing else to track here.
module.exports = {
    nets: {
        net: undefined
    },
    params: {
        class: 'MP',
        designator: 'H',
    },
    body: p => `
    (footprint "MountingHole_2.2mm_M2_Pad_Via"
      (layer "F.Cu")
      (descr "Mounting Hole 2.2mm, M2, generated by kicad-footprint-generator mountinghole.py")
      (tags "mountinghole M2")
      ${p.at /* parametric position */}
      (attr exclude_from_pos_files exclude_from_bom)
      (fp_text reference "${p.ref}" (at 0 -3.15 0) (layer "F.SilkS") ${p.ref_hide}
        (effects (font (size 1 1) (thickness 0.15)))
      )
      (fp_text value "MountingHole_2.2mm_M2_Pad_Via" (at 0 3.15 0) (layer "F.Fab")
        (effects (font (size 1 1) (thickness 0.15)))
      )
      (fp_circle (center 0 0) (end 2.2 0) (stroke (width 0.15) (type solid)) (fill no) (layer "Cmts.User"))
      (fp_circle (center 0 0) (end 2.45 0) (stroke (width 0.05) (type solid)) (fill no) (layer "F.CrtYd"))
      (pad "1" thru_hole circle (at -1.65 0) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at -1.166726 -1.166726) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at -1.166726 1.166726) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at 0 -1.65) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at 0 0) (size 4.4 4.4) (drill 2.2) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at 0 1.65) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at 1.166726 -1.166726) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at 1.166726 1.166726) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
      (pad "1" thru_hole circle (at 1.65 0) (size 0.7 0.7) (drill 0.4) (layers "*.Cu" "*.Mask") (zone_connect 2))
    )`
}
